In [1]:
import numpy as np
import pandas as pd

In [9]:
## Reshape
original_array = np.array([[[1, 2,1], [3, 4,1]],
                            [[5, 6, 2], [7, 8, 2]],
                            [[9, 10, 1 ], [11, 12, 1]]])


In [10]:
print(original_array)

[[[ 1  2  1]
  [ 3  4  1]]

 [[ 5  6  2]
  [ 7  8  2]]

 [[ 9 10  1]
  [11 12  1]]]


In [11]:
print("original shape", original_array.shape)

original shape (3, 2, 3)


In [12]:
flattened_array = original_array.reshape(-1) 

In [13]:
print("after reshape", flattened_array.shape)

after reshape (18,)


In [14]:
print(flattened_array)

[ 1  2  1  3  4  1  5  6  2  7  8  2  9 10  1 11 12  1]


In [15]:
restored_array = flattened_array.reshape(original_array.shape)

In [16]:
print("restored shape", restored_array.shape)

restored shape (3, 2, 3)


In [17]:
print(restored_array)

[[[ 1  2  1]
  [ 3  4  1]]

 [[ 5  6  2]
  [ 7  8  2]]

 [[ 9 10  1]
  [11 12  1]]]


In [18]:
print(original_array)

[[[ 1  2  1]
  [ 3  4  1]]

 [[ 5  6  2]
  [ 7  8  2]]

 [[ 9 10  1]
  [11 12  1]]]


3

In [20]:
original_array.reshape(original_array.shape[0], 2*3)

array([[ 1,  2,  1,  3,  4,  1],
       [ 5,  6,  2,  7,  8,  2],
       [ 9, 10,  1, 11, 12,  1]])

In [21]:
for i in range(3):
    print(i)

0
1
2


In [23]:
y = np.zeros(5)

In [24]:
print(y)

[0. 0. 0. 0. 0.]


In [25]:
# argmin 
# Return the index of min value of the array

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

min_index = np.argmin(arr)

print(min_index)  

1


In [26]:
# for ndarray

arr = np.array([[3, 1, 4],
                [1, 5, 9],
                [2, 6, 5]])


min_indices = np.argmin(arr, axis=1)

print(min_indices) 


[1 0 0]


In [1]:
# keepdims param
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# sum and keep dims
sum_result = np.sum(arr, axis=1, keepdims=True)

print("Original array shape:", arr.shape)
print("Sum result shape with keepdims=True:", sum_result.shape)
print("Sum result with keepdims=True:")
print(sum_result)


Original array shape: (2, 3)
Sum result shape with keepdims=True: (2, 1)
Sum result with keepdims=True:
[[ 6]
 [15]]


In [2]:
# sum and not keep dims
sum_result_no_keepdims = np.sum(arr, axis=1)

print("Sum result shape with keepdims=False:", sum_result_no_keepdims.shape)
print("Sum result with keepdims=False:")
print(sum_result_no_keepdims)


Sum result shape with keepdims=False: (2,)
Sum result with keepdims=False:
[ 6 15]


In [3]:
sum_with_keepdims = np.sum(arr, axis=1, keepdims=True)
sum_without_keepdims = np.sum(arr, axis=1)

In [4]:
print(sum_with_keepdims)

[[ 6]
 [15]]


In [5]:
print(sum_without_keepdims)

[ 6 15]


In [8]:
A = np.array([[1, 2],
              [3, 4]])

In [9]:
A*A

array([[ 1,  4],
       [ 9, 16]])

In [10]:
A.dot(A.T)

array([[ 5, 11],
       [11, 25]])

In [11]:
sum(A)

array([4, 6])

In [14]:
np.sum(A, axis=1)

array([3, 7])

In [15]:
# argsort - return the top k nearest index
import numpy as np

distances = np.array([3.2, 1.5, 2.7, 4.0, 0.8])

K = 3
nearest_indices = np.argsort(distances)[:K]

print(nearest_indices)


[4 1 2]


In [22]:
# bincount and argmax
arr = np.array([7, 3, 3, 3, 4, 4, 4, 4, 4])

counts = np.bincount(arr)
most_common_value = np.argmax(counts)

print("Array:", arr)
print("Counts:", counts)
print("Most common value:", most_common_value)


Array: [7 3 3 3 4 4 4 4 4]
Counts: [0 0 0 3 5 0 0 1]
Most common value: 4


In [23]:
# array_split

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


sub_arrays = np.array_split(arr, 3)
print(sub_arrays)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [24]:

sub_arrays = np.array_split(arr, [2, 5])
print(sub_arrays)


[array([1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [25]:
# enumerate
fruits = ['apple', 'banana', 'cherry']

for index, fruit in enumerate(fruits):
    print(f"Index {index}: {fruit}")

Index 0: apple
Index 1: banana
Index 2: cherry


i = 1
selected_folds = []
for j, fold in enumerate(fruits):
    if i!=j:
        selected_folds.append(fold)

print(selected_folds)

In [29]:
i=0
my_folds = [fold for j, fold in enumerate(fruits) if i !=j]
print(my_folds)

['banana', 'cherry']


In [ ]:
# https://github.com/jariasf/CS231n/blob/master/assignment1/cs231n/classifiers/linear_svm.py