In [1]:
import numpy as np
import pandas as pd

In [9]:
## Reshape
original_array = np.array([[[1, 2,1], [3, 4,1]],
                            [[5, 6, 2], [7, 8, 2]],
                            [[9, 10, 1 ], [11, 12, 1]]])


In [10]:
print(original_array)

[[[ 1  2  1]
  [ 3  4  1]]

 [[ 5  6  2]
  [ 7  8  2]]

 [[ 9 10  1]
  [11 12  1]]]


In [11]:
print("original shape", original_array.shape)

original shape (3, 2, 3)


In [12]:
flattened_array = original_array.reshape(-1) 

In [13]:
print("after reshape", flattened_array.shape)

after reshape (18,)


In [14]:
print(flattened_array)

[ 1  2  1  3  4  1  5  6  2  7  8  2  9 10  1 11 12  1]


In [15]:
restored_array = flattened_array.reshape(original_array.shape)

In [16]:
print("restored shape", restored_array.shape)

restored shape (3, 2, 3)


In [17]:
print(restored_array)

[[[ 1  2  1]
  [ 3  4  1]]

 [[ 5  6  2]
  [ 7  8  2]]

 [[ 9 10  1]
  [11 12  1]]]


In [18]:
print(original_array)

[[[ 1  2  1]
  [ 3  4  1]]

 [[ 5  6  2]
  [ 7  8  2]]

 [[ 9 10  1]
  [11 12  1]]]


3

In [20]:
original_array.reshape(original_array.shape[0], 2*3)

array([[ 1,  2,  1,  3,  4,  1],
       [ 5,  6,  2,  7,  8,  2],
       [ 9, 10,  1, 11, 12,  1]])

In [21]:
for i in range(3):
    print(i)

0
1
2


In [23]:
y = np.zeros(5)

In [24]:
print(y)

[0. 0. 0. 0. 0.]


In [25]:
# argmin 
# Return the index of min value of the array

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

min_index = np.argmin(arr)

print(min_index)  

1


In [26]:
# for ndarray

arr = np.array([[3, 1, 4],
                [1, 5, 9],
                [2, 6, 5]])


min_indices = np.argmin(arr, axis=1)

print(min_indices) 


[1 0 0]
